# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Demo' do
  pod 'OAuthCore'
end

plugin 'cocoapods-keys', {
    :project => 'dk-tw-reverse-auth-demo',
    :keys => [
    'TwitterConsumerKey',
    'TwitterConsumerSecret'
    ]
}
